# Generated by Django 3.2.18 on 2023-02-18 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20230218_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoallproxy',
            options={'verbose_name': 'All Video', 'verbose_name_plural': 'All Videos'},
        ),
    ]
