# Generated by Django 3.2.18 on 2023-02-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20230218_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='published_timestamp',
            new_name='publish_timestamp',
        ),
    ]
